### ISSUE TITLE
Strange behavior when updating tree using asynchronous data

### ISSUE THREAD

**Issue by lvyandev** [mbaumgartenbr/flutter_tree_view#11]
In some situations, we need to fetch tree children from server before expand.

```dart
late final _dynamicController = TreeViewController(
    onAboutToExpand: (TreeNode nodeAboutToExpand) async {
      if (treeController != _dynamicController) return;

      // add this line
      await Future.delayed(const Duration(milliseconds: 300));

      final children = _dynamicChildrenMap[nodeAboutToExpand.id];

      if (children != null) {
        nodeAboutToExpand.addChildren(
          children.map((child) => TreeNode(id: child, label: child)),
        );
      }
    },
    rootNode: TreeNode(id: 'Root')
      //? Initial Dynamic Nodes
      ..addChild(TreeNode(id: 'A', label: 'A'))
      ..addChild(TreeNode(id: 'B', label: 'B'))
      ..addChild(TreeNode(id: 'C', label: 'C')),
  );
```
Then it behave like this, I need to retap the expander to let the tree update.

https://user-images.githubusercontent.com/18045999/120623484-59745e80-c492-11eb-951a-0329a60e786e.mp4

Am I using it wrong way? How should I update the treeView after load data async.

**Comment by mbaumgartenbr** [comment]
Hey!

I didn't plan `onAboutToExpand` tp be a future...
So `expandNode` doesn't await on it.

`onAboutToExpand` should be syncronous for now.

I'm currently working on a `refreshNode` feature that's almost done, I just have to run some more tests on it.

**Comment by lvyandev** [comment]
So `refreshNode` should be a function that can update a specific node in the tree?

**Comment by mbaumgartenbr** [comment]
Yes, and the entire subtree of that node with an option to keep the expanded nodes.

**Comment by lvyandev** [comment]
With that should be enough for now.
Hope to see it soon

**Comment by mbaumgartenbr** [comment]
And probably with `refreshNode` we wouldn't need `onAboutToExpand` anymore because we could do children fetching from `NodeWidget` asynchronously showing a progress indicator and when that's done, call `refreshNode` and be all good.

**Comment by lvyandev** [comment]
I agree with that. Since `onAboutToExpand ` doesn't support async.

**Comment by jonahzheng** [comment]
I have the same problam, I want click Folder icon, get data from server api, add childs for node dynamic, and expand node.
onAboutToExpand dose not seem to support async.

![@3SWZX@$)3(9GA9K_VQ)O17](https://user-images.githubusercontent.com/5125282/177231995-6752f050-d20a-434c-8dce-7769ce40fcc2.png)
