### ISSUE TITLE
how to select parent and all children ?

### ISSUE THREAD

**Issue by huanlirui** [mbaumgartenbr/flutter_tree_view#13]
i want select parent and all chidren and children's children ....

**Comment by mbaumgartenbr** [comment]
Hi!

You can use the `TreeNode.descendants` getter, it will iterate through the entire subtree of that node.

```dart
for (final node in myNode.descendants) {
  yourSelectMethod(node);
}

// Or

myNode.descendants.forEach(yourSelectMethod);
```

The TreeView doesn't handle selection on purpose, that state is up to you to handle.

Hope it helps!
