### ISSUE TITLE
right-to-left treeview

### ISSUE THREAD

**Issue by fn-19** [mbaumgartenbr/flutter_tree_view#14]
hi, thanks for share your code, this help me a lot.
just I have question: I want to set right-to-left tree, but I cannot found how to change line in tree.
How can I do this?

**Comment by mbaumgartenbr** [comment]
Hi @fn-19, thank you for trying out the package!

Unfortunately in the current API it is not possible to change the Directionality of the lines.

But thank you for opening this issue, I'll work on it as soon as I have time, I'm currently working on another project, so I can't promise that it's going to be done in the near future.

If you'd like to submit a PR I'd appreciate it!

**Comment by mbaumgartenbr** [comment]
Hi @fn-19! I started working on the next version of the package.

To achieve RTL it will be as easy as having a `Directionality` widget somewhere before the `TreeView` in the widget tree.

![Directionality Screenshot](https://user-images.githubusercontent.com/58597459/139719373-124bd85a-3bfd-43f1-8a36-e7bbf1b46950.png)

As I'm also working on another features, it will take some time for the new version to land.

**Comment by naory159** [comment]
@mbaumgartenbr you can close this issue
