### ISSUE TITLE
Is there an physics in TreeView?

### ISSUE THREAD

**Issue by DuongQuocHai** [mbaumgartenbr/flutter_tree_view#15]
Have a nice day, your library is very good and I am using it in my project.
But I have a problem, shouldAutoScroll: true when I select the last node in the list, the treeView will be pushed up unnecessarily. Is there any way to fix it?

**Comment by mbaumgartenbr** [comment]
Hi!

The scrolling feature was removed in version 0.5.0, you must handle scrolling yourself.

The old scrolling mechanism was pretty bad, I just put it together quickly.

I have plans of reimplementing it in the future, but I currently have no time to work on it.
