### ISSUE TITLE
Change TreeView when use StreamBuilder

### ISSUE THREAD

**Issue by GomeDev** [mbaumgartenbr/flutter_tree_view#2]
Hi, thank you for awesome package!
In my project, I use StreamBuilder to change data (create, delete, edit) but TreeView not displayed according to new data. What I have to do?
Thank.

**Comment by mbaumgartenbr** [comment]
Hey @GomeDev! Thanks for trying the package out.

I'm currently rewriting the API to make it a little less expensive for drawing widgets, currently it rebuilds every single node in the tree when the list changes and that's not performing very well. I'm almost done with it.

For your use case, I would need some code example to see how you're building your tree.

_I guess the blame is on me for not writing the documentation yet 🤷‍♂️._

**Comment by GomeDev** [comment]
Hi @mbaumgartenbr , Thank for your support!
Here is my class use TreeView
`class LocationPage extends StatefulWidget {
  @override
  _LocationPageState createState() => _LocationPageState();
}

class _LocationPageState extends State<LocationPage> {
  TreeViewController treeController;
  TreeNode rootNode;
  TreeViewTheme treeTheme = TreeViewTheme(
    nodeSelectedTileColor: Colors.grey.shade300,
    lineStyle: LineStyle.scoped,
  );
  BlocLocation blocLocation;

  @override
  void initState() {
    blocLocation = BlocProvider.of(context);
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    const iconColor = Colors.blue;
    return Scaffold(
      backgroundColor: AppConstants.bgPrimary,
      body: Container(
        padding: EdgeInsets.only(right: 10.0, left: 10.0),
        child: StreamBuilder<List<Location>>(
            initialData: BlocLocation.nestedLocations,
            stream: blocLocation.streamListLocation,
            builder: (context, snapLocations) {
              print("run");
              print(snapLocations.data.length);
              rootNode = generateTreeNodes(snapLocations.data);
              treeController = new TreeViewController(rootNode: rootNode);
              return new TreeView(
                controller: treeController,
                theme: treeTheme,
                nodeBuilder: (_, node) {
                  print("nodeBuilder ${node.data.name}");
                  return new NodeWidget(
                    node: node,
                    theme: treeTheme,
                    title: Row(
                      children: [
                        Padding(
                          padding: const EdgeInsets.only(left: 2, right: 8),
                          child: node.hasChildren
                              ? const Icon(Icons.folder_rounded, color: iconColor)
                              : const Icon(Icons.folder_open_rounded, color: iconColor),
                        ),
                        // Flexible(child: Text(node.data as String)),
                        Flexible(child: Text(node.data.name)),
                      ],
                    ),
                    onTap: () {
                      addNewLocation(node.data, context, blocLocation);
                      // deleteLocation(node.data, context, blocLocation);
                    },
                  );
                },
              );
            }
        ),
      ),
    );
  }
}

List<TreeNode> mapHierarchicalData(List<Location> locations,) {

  List<TreeNode> nodes = [];

  locations.forEach((element) {
    // if (element.children.isEmpty) return const [];
    final node = new TreeNode(
      id: element.intId,
      data: element,
    );
    nodes.add(node);
    if (element.children.isNotEmpty) {
      node.addChildren(mapHierarchicalData(element.children));
    }
  });
  return nodes;
}

TreeNode generateTreeNodes(List<Location> maps) {
  // return new TreeNode(data: 'Root')..addChildren(mapHierarchicalData(maps));
  TreeNode treeNode = new TreeNode(
      data: "Root",
      id: 1
  );
  List<TreeNode> nodes = mapHierarchicalData(maps);
  print("generateTreeNodes ${nodes.length}");
  treeNode.addChildren(nodes);
  return treeNode;
}`

When i perform add or delete, I realize that [snapLocations] and [rootNode] do change with new data but [nodeBuilder] still receives old data.
Thank!

**Comment by mbaumgartenbr** [comment]
Hy @GomeDev! I'm not sure why this would happen, you're creating and entire new controller and root node... As I'm rewriting the API, most of the code will change, perhaps this issue is fixed in the nee version.

I'm in the last steps to releasing the new version.

Later today I will take a look at your code and try to replicate it.

Thanks for trying the package out!

**Comment by mbaumgartenbr** [comment]
Found the problem! I'm pretty sure this will work in the new API.

Thanks to your issue, I was able to find another problem with the API. 😊

**Comment by GomeDev** [comment]
Thanks you, hope your new API will help my problem.
Thanks for good package, have a nice day!!!

**Comment by AL-YAFEA-KHALED** [comment]
> 
Hi sir if don't mind can you please share with me how you build your location list and how it's connected with sublists. Thanks
