### ISSUE TITLE
how add childs for node dynamic?

### ISSUE THREAD

**Issue by jonahzheng** [mbaumgartenbr/flutter_tree_view#26]
I have the same problam, I want click Folder icon, get data from server api, add childs for node dynamic, and auto expand the node.
onAboutToExpand dose not seem to support async.

![image](https://user-images.githubusercontent.com/5125282/177232164-0566b669-6be7-4209-acfd-e83bf5466121.png)

#11

**Comment by mbaumgartenbr** [comment]
Hey @jonahzheng!

The expected way of lazy loading is to create a "CustomNodeWidget" widget, wrapping "NodeWidget" in a StatefullWidget, then keep track of a variable that checks if the node's children have been fetched, then pass a `onTap` callback to "NodeWidget" that checks the variable and fetches and/or toggles the node expansion state.

To add children to a node that already has children, update the nodes accordingly and call `treeController.refreshNode(node)`.

**Comment by jonahzheng** [comment]
@mbaumgartenbr Thank for you replay,
you right, my code is
```
      NodeWidgetLeadingIcon(
        useFoldersOnly: true,
        onPressed: () async {
            List<String> childrenIds = [];
            childrenIds =await getChilds(node.id);

            node.addChildren(
              childrenIds.map((String childId) {
                return TreeNode(id: childId, label: childId);
              }),
            );
            treeController.refreshNode(node, keepExpandedNodes: true);
        },
      ),
```
