### ISSUE TITLE
Nodes with a higher content than normal (eg. multi-line text)

### ISSUE THREAD

**Issue by JostSchenck** [mbaumgartenbr/flutter_tree_view#29]
Great package! Do I understand this right, that all nodes are supposed to have the same height? Would it be possible to include a column of widgets or multi-line text, with the treeview adapting to this?
Thanks a lot!

**Comment by mbaumgartenbr** [comment]
Hey @JostSchenck! Thank you for using the package.

Unfortunately yes, all nodes must have a fixed height with the current API.

But with the new version that I'm working on, this restriction will be gone. I can't promise it will be out soon as I'm still figuring some reordering APIs out (and I'm currently on vacation).

**Comment by JostSchenck** [comment]
Ah, that's great to hear, thank you!

**Comment by amorenew** [comment]
@mbaumgartenbr Is the next release still will contain the dynamic height?

**Comment by mbaumgartenbr** [comment]
> @mbaumgartenbr Is the next release still will contain the dynamic height?

Sure!

**Comment by amorenew** [comment]
@mbaumgartenbr 
A sample of what I did by your library,
Thanks for your effort
![Screenshot 2022-11-20 at 2 02 30 PM](https://user-images.githubusercontent.com/2842459/202900767-a751e0eb-d837-4e37-a6e9-f96a6f7edd8d.png)

![Screenshot 2022-11-20 at 2 03 37 PM](https://user-images.githubusercontent.com/2842459/202900815-7398d90a-d43e-4917-a607-62429d743fff.png)

**Comment by mbaumgartenbr** [comment]
Wow @amorenew, thats looking great!

Thank you for sharing! I really appreciate it 😊

**Comment by amorenew** [comment]
You're welcome 😍

**Comment by amorenew** [comment]
@mbaumgartenbr I wonder if you could make the line dynamic too so it won't go far away when widgets have dynamic sizes 

<img width="544" alt="Screenshot 2022-11-20 at 5 58 13 PM" src="https://user-images.githubusercontent.com/2842459/202912300-0414238b-42a3-414e-858e-ff4c1864cb74.png">
<img width="625" alt="Screenshot 2022-11-20 at 6 01 33 PM" src="https://user-images.githubusercontent.com/2842459/202912394-04d7424f-7f7f-4737-abaf-862f066e771a.png">

**Comment by mbaumgartenbr** [comment]
Hey @amorenew. Thank you for pointing that out. I'm aware of this behavior and the fix should be straight forward. I might be able to squeeze it in #35 but I can't promise anything since I have very little spare time to work on this package.
