### ISSUE TITLE
Possibly to add events for Expanding/expanded Closing/closed?

### ISSUE THREAD

**Issue by MagnusJohansson** [mbaumgartenbr/flutter_tree_view#3]
I just found this and it looked promising.

However, my requirement is that I need to load dynamic data(nodes) whenever a node is expanded on the fly.
I.e. not limited to a static data set.

Would this be possible to add?

**Comment by mbaumgartenbr** [comment]
I was thinking about it when refactoring the API...

My first thoughts were to make a new TreeView called AsyncTreeVIew or DynamicTreeView to accommodate such feature.
Most of the implementation would depend on _ids_ and _parentIds_.

But it is totally doable, it's going to require a bit of planning and experimentation.

Would you have any recommendation of approaches for this feature?
