### ISSUE TITLE
Library building

### ISSUE THREAD

**Issue by amorenew** [mbaumgartenbr/flutter_tree_view#37]
Hello Matheus Baumgarten ,

I need to make complex views, How could I make a similar complex library like yours from scratch?
What do I need to learn to master complex views?

<img width="100" src="https://user-images.githubusercontent.com/2842459/203027781-6b71293c-bb12-4c24-bf0c-5eb9834a78cf.png">

**Comment by mbaumgartenbr** [comment]
Hey @amorenew!

To be honest, I don't know 🤷‍♂️. It depends on a lot of stuff, like, how much time are you willing to put on the project, how much knowledge you have on the domain, is te project going to add value to your work/life in any way?, etc.

I'm not the person to answer this kind of question, sorry 😬.

**Comment by amorenew** [comment]
Thanks a lot for your answer and effort in this library
