### ISSUE TITLE
Autoscroll to node?

### ISSUE THREAD

**Issue by pbeccegato** [mbaumgartenbr/flutter_tree_view#7]
I've implemented your treeview in my project and it works fine so, by first, many thanks for your job.
In some case, I have very extended trees, so I would like to implement a function to search a node, using for example the "find" method and than autoscroll to tree view to that node. Is there some method that can I use fo this?

**Comment by mbaumgartenbr** [comment]
Thank you for trying the package out!

I was thinking about it the other day and it's totally possible because we have both the index and height of nodes to calculate the offset in the scrollview. 

I'll get into it as soon as possible!

**Comment by jaxnz** [comment]
@mbaumgartenbr can you please explain how this would work? Documentation is confusing

**Comment by mbaumgartenbr** [comment]
Hey @jaxnz!

The current version of the package doesn't support scrolling to nodes.
